### ISSUE TITLE
Instagram live feeds ???

### ISSUE THREAD

**Issue by norsasono** [muan/muan.github.com#10]
How can I use the instagram live feed like @muan does? I've changed the used ID and client ID, but nothing happened, just blank.

**Comment by muan** [comment]
Note [here](https://github.com/norsasono/norsasono.github.io/blob/09fe03145f43a87399d6b16c5f5761a918ae4260/_assets/stuff.coffee#L21-L22) I filter the the images with emails that has the tag `#_`. If you just change those 2 lines to `window.pics = data.data` and recompile, you'll get all the images. Alternatively, you can start adding `#_` to your instagram pictures to select the ones you want on the site.
