### ISSUE TITLE
Use your theme

### ISSUE THREAD

**Issue by mrjk05** [muan/muan.github.com#14]
I really like your jekyll theme. I was wondering how I would use it?
When i try to run bundle i get the error, Could not locate Gemfile or .bundle/ directory

**Comment by Linkerist** [comment]
The girl is so beautiful .

**Comment by muan** [comment]
Hi @mrjk05, sorry for completely dropping the ball here. I've updated the readme. :)

**Comment by istx25** [comment]
@Linkerist: Was your comment _really_ necessary?

<img width="784" alt="screen shot 2017-03-01 at 15 38 24" src="https://cloud.githubusercontent.com/assets/6799989/23480210/26696a0c-fe95-11e6-9583-c79463f2820b.png">

Can you, like, not?

**Comment by istx25** [comment]
Thanks @muan for opening up this theme to the community. It's really awesome! :)
